version: '3.9'
services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
  gateway:
    build: ../backend/api-gateway
    ports: ["8080:8080"]
    depends_on: [auth, catalog, order, payment, tracking]
  auth:
    build: ../backend/auth-user-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/momsbakery_auth
    depends_on: [mongo]
  catalog:
    build: ../backend/catalog-inventory-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/momsbakery_catalog
    depends_on: [mongo]
  order:
    build: ../backend/order-cart-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/momsbakery_order
    depends_on: [mongo]
  payment:
    build: ../backend/payment-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/momsbakery_payment
    depends_on: [mongo]
  tracking:
    build: ../backend/tracking-notification-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/momsbakery_tracking
    depends_on: [mongo]
